name: main

on:
  push:
  # `workflow_call` is used by the tag workflow to trigger the `build` job
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Use `fetch-depth: 0` otherwise `git describe` does not see valid
          # tags, causing ci/create-archive to create snapshot archives. This
          # also requires the "Fix actions/checkout bug" step below to work.
          fetch-depth: 0

      # See https://github.com/actions/checkout/issues/290#issuecomment-680260080
      - name: Fix actions/checkout bug
        run: git fetch --force --tags

      - name: Build
        run:
          echo "Building $GITHUB_REF" > result.txt

      - name: Read info
        id: info
        shell: bash
        run: |
          VERSION=$(git describe)
          echo VERSION=$VERSION
          [ -n "$VERSION" ]
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create artifacts
        run: |
          [ -n "$VERSION" ]
          mkdir -p artifacts
          zip artifacts/dummy-$VERSION.zip README.md LICENSE result.txt
          tar czf artifacts/dummy-$VERSION.tar.gz README.md LICENSE result.txt
        env:
          VERSION: ${{ steps.info.outputs.VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts
