name: Build

on:
  push:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run:
          echo "Building $GITHUB_REF" > result.txt

      - name: Read info
        id: info
        shell: bash
        run: |
          echo "VERSION=$(git describe)" >> $GITHUB_OUTPUT

      - name: Create artifacts
        run: |
          [ -n "$VERSION" ]
          mkdir -p artifacts
          zip artifacts/dummy-$VERSION.zip README.md LICENSE result.txt
          tar czf artifacts/dummy-$VERSION.tar.gz README.md LICENSE result.txt
        env:
          VERSION: ${{ steps.info.outputs.VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts
