name: Application Release

on:
  push:
    tags:
      - '[0-9]*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read info
        id: info
        shell: bash
        run: |
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Create artifacts
        run: |
          [ -n "$TAG" ]
          mkdir -p artifacts
          zip artifacts/dummy-$TAG.zip README.md LICENSE
          tar czf artifacts/dummy-$TAG.tar.gz README.md LICENSE
        env:
          TAG: ${{ steps.info.outputs.tag }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            artifacts

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Read info
        id: info
        shell: bash
        run: |
          echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts

      - name: Create release
        run: |
          ls
          ls artifacts
          gh release create --draft --verify-tag "$TAG" artifacts/dummy-$TAG.*
        env:
          TAG: ${{ steps.info.outputs.tag }}
          GH_TOKEN: ${{ github.token }}
